language: objective-c
osx_image: xcode8
xcode_sdk: macosx10.12
before_script: xcodebuild -version
script: xcodebuild -project BitbucketInbox/BitbucketInbox.xcodeproj -scheme BitbucketInbox build test
