language: objective-c
osx_image: xcode8
podfile: Sources/Podfile
before_install: travis_wait pod repo update --silent
script: xcodebuild -workspace Sources/PR.xcworkspace -scheme PR clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
